const coursesAndBranches = {
    "B.Tech/B.E.": [
      "Computer Science and Engineering",
      "Mechanical Engineering",
      "Electrical and Electronics Engineering",
      "Civil Engineering",
      "Electronics and Communication Engineering",
      "Information Technology",
      "Chemical Engineering",
      "Biotechnology",
      "Data Science",
      "Artificial Intelligence and Machine Learning",
      "Aerospace Engineering",
    ],
    "B.Sc.": [
      "Physics",
      "Chemistry",
      "Mathematics",
      "Zoology",
      "Botany",
      "Biotechnology",
      "Computer Science",
      "Environmental Science",
      "Microbiology",
      "Statistics",
    ],
    "B.Com": [
      "Accounting and Finance",
      "Banking and Insurance",
      "Taxation",
      "International Business",
      "Business Analytics",
      "Marketing",
    ],
    "B.A.": [
      "English",
      "History",
      "Political Science",
      "Sociology",
      "Psychology",
      "Economics",
      "Philosophy",
      "Journalism and Mass Communication",
      "Public Administration",
    ],
    "BCA": [
      "Computer Applications",
      "Software Development",
      "Information Systems",
      "Data Analytics",
      "Cybersecurity",
    ],
    "BBA": [
      "Marketing",
      "Finance",
      "Human Resource Management",
      "Operations Management",
      "Information Technology",
      "Business Analytics",
      "Entrepreneurship",
      "International Business",
      "Healthcare Management",
    ],
    "B.Arch": [
      "Urban Design",
      "Landscape Architecture",
      "Sustainable Architecture",
      "Construction Management",
    ],
    "B.Des": [
      "Industrial Design",
      "Communication Design",
      "Product Design",
      "Fashion Design",
      "User Experience (UX) Design",
    ],
    "B.Pharm": [
      "Pharmaceutics",
      "Pharmacology",
      "Pharmaceutical Chemistry",
      "Pharmacy Practice",
      "Pharmacognosy",
    ],
    "LLB": [
      "Corporate Law",
      "Constitutional Law",
      "Criminal Law",
      "Intellectual Property Rights",
      "International Law",
    ],
    "B.Ed": [
      "Curriculum and Instruction",
      "Educational Psychology",
      "Special Education",
      "Educational Technology",
      "Teacher Training",
    ],
    "B.F.A.": [
      "Painting",
      "Sculpture",
      "Applied Arts",
      "Photography",
      "Visual Arts",
    ],
    "B.J.M.C.": [
      "Broadcast Journalism",
      "Print Journalism",
      "Digital Media",
      "Public Relations",
      "Advertising",
    ],
    "BDS": [
      "Orthodontics",
      "Prosthodontics",
      "Oral and Maxillofacial Surgery",
      "Pedodontics",
      "Periodontics",
    ],
    "BPT": [
      "Orthopedics",
      "Neurology",
      "Sports Physiotherapy",
      "Cardiopulmonary",
    ],
    "B.V.Sc.": [
      "Animal Nutrition",
      "Veterinary Medicine",
      "Livestock Production Management",
      "Veterinary Surgery",
    ],
    "B.S.W.": [
      "Community Development",
      "Human Resource Management",
      "Medical and Psychiatric Social Work",
      "Rural Development",
    ],
    "B.H.M.": [
      "Hospitality Management",
      "Tourism Management",
      "Food and Beverage Management",
      "Event Management",
    ],
  };
  
  export default coursesAndBranches;
  